// Copyright Voxel Plugin, Inc. All Rights Reserved.

#pragma once

#include "VoxelEditorMinimal.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphSchema.h"
#include "VoxelGraphSchema.generated.h"

class SGraphPin;
class FVoxelGraphEditorToolkit;
class UVoxelGraphFunctionNode;
class UVoxelGraphFunctionLibrary;

UCLASS(Abstract)
class VOXELGRAPHEDITOR_API UVoxelGraphSchema : public UEdGraphSchema
{
	GENERATED_BODY()
	
public:
	static void OnGraphChanged(const UEdGraphPin* Pin);
	static void OnGraphChanged(const UEdGraphNode* Node);
	static void OnGraphChanged(const UEdGraph* Graph);

	static TSharedPtr<FVoxelGraphEditorToolkit> GetToolkit(const UEdGraph* Graph);

public:
	bool ConnectionCausesLoop(const UEdGraphPin* InputPin, const UEdGraphPin* OutputPin) const;
	bool CanCreateAutomaticConversionNode(const UEdGraphPin* PinA, const UEdGraphPin* PinB) const;

	virtual TSharedPtr<FEdGraphSchemaAction> FindCastAction(const FEdGraphPinType& From, const FEdGraphPinType& To) const
	{
		return nullptr;
	}
	virtual TOptional<FPinConnectionResponse> GetCanCreateConnectionOverride(const UEdGraphPin* PinA, const UEdGraphPin* PinB) const
	{
		return {};
	}
	virtual bool HasExecBehavior(const FEdGraphPinType& Type) const
	{
		return false;
	}
	virtual bool CreatePromotedConnectionSafe(UEdGraphPin*& PinA, UEdGraphPin*& PinB) const
	{
		return false;
	}

public:
	//~ Begin UEdGraphSchema Interface
	virtual void GetGraphContextActions(FGraphContextMenuBuilder& ContextMenuBuilder) const override;
	virtual bool CreateAutomaticConversionNodeAndConnections(UEdGraphPin* PinA, UEdGraphPin* PinB) const override;
	
	virtual const FPinConnectionResponse CanCreateConnection(const UEdGraphPin* PinA, const UEdGraphPin* PinB) const override;
	virtual bool TryCreateConnection(UEdGraphPin* PinA, UEdGraphPin* PinB) const override;
	virtual bool CreatePromotedConnection(UEdGraphPin* PinA, UEdGraphPin* PinB) const final override;

	virtual TSharedPtr<FEdGraphSchemaAction> GetCreateCommentAction() const override;
	virtual int32 GetNodeSelectionCount(const UEdGraph* Graph) const override;
	virtual void GetContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const override;
	virtual void ResetPinToAutogeneratedDefaultValue(UEdGraphPin* Pin, bool bCallModifyCallbacks = true) const override;
	virtual void CreateDefaultNodesForGraph(UEdGraph& Graph) const override;

	virtual void BreakNodeLinks(UEdGraphNode& TargetNode) const override;
	virtual void BreakPinLinks(UEdGraphPin& TargetPin, bool bSendsNodeNotification) const override;

	virtual void TrySetDefaultValue(UEdGraphPin& Pin, const FString& NewDefaultValue, bool bMarkAsModified) const override;
	virtual void TrySetDefaultObject(UEdGraphPin& Pin, UObject* NewDefaultObject, bool bMarkAsModified) const override;

	virtual bool ShouldHidePinDefaultValue(UEdGraphPin* Pin) const override;
	virtual bool ShouldAlwaysPurgeOnModification() const override { return false; }
	//~ End UEdGraphSchema Interface
};