// Copyright Voxel Plugin, Inc. All Rights Reserved.

#include "Common.ush"

uint Num;
float HalfStep;
Buffer<float> Values;
RWBuffer<float> OutValues;

[numthreads(64, 1, 1)]
void Main(uint DispatchThreadId : SV_DispatchThreadID)
{
	if (DispatchThreadId >= Num)
	{
		return;
	}

	OutValues[2 * DispatchThreadId + 0] = Values[DispatchThreadId] - HalfStep;
	OutValues[2 * DispatchThreadId + 1] = Values[DispatchThreadId] + HalfStep;
}